// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anmidbjnsbcdlhkwgikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubWlkYmpuc2JjZGxoa3dnaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDQ2MzUsImV4cCI6MjA2NDk4MDYzNX0.aSrCrwjDVNAobVBkNV0aFDCGQjRdaIAllNu3sYXW2nA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);